-- Pioneers Chess Academy Database Schema
-- Roles: 'admin', 'instructor', 'student', 'parent'

-- Users Table
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role VARCHAR(20) CHECK (role IN ('admin', 'instructor', 'student', 'parent')) NOT NULL,
    full_name TEXT NOT NULL,
    phone_number TEXT,
    avatar_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Profiles (for role-specific details)
CREATE TABLE instructor_profiles (
    user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    bio TEXT,
    chess_title VARCHAR(50), -- GM, IM, FM, etc.
    hourly_rate DECIMAL(10, 2) DEFAULT 0.00,
    google_calendar_token TEXT -- For syncing availability if needed
);

CREATE TABLE student_profiles (
    user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    date_of_birth DATE,
    current_rating INTEGER DEFAULT 800,
    lichess_username TEXT,
    chesscom_username TEXT,
    parent_id UUID REFERENCES users(id) -- Linking to parent account
);

-- Courses / Curriculums
CREATE TABLE courses (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    title TEXT NOT NULL,
    description TEXT,
    level VARCHAR(50) CHECK (level IN ('beginner', 'intermediate', 'advanced')),
    price DECIMAL(10, 2),
    duration_weeks INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Classes (Scheduled Sessions)
CREATE TABLE classes (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    course_id UUID REFERENCES courses(id),
    instructor_id UUID REFERENCES users(id),
    title TEXT NOT NULL,
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    end_time TIMESTAMP WITH TIME ZONE NOT NULL,
    google_meet_link TEXT, -- Generated by backend
    meet_link_visible_at TIMESTAMP WITH TIME ZONE, -- 10 mins before start
    status VARCHAR(20) DEFAULT 'scheduled', -- scheduled, ongoing, completed, cancelled
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enrollments
CREATE TABLE enrollments (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    course_id UUID REFERENCES courses(id),
    student_id UUID REFERENCES users(id),
    enrolled_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Attendance
CREATE TABLE attendance (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    class_id UUID REFERENCES classes(id),
    student_id UUID REFERENCES users(id),
    status VARCHAR(20) CHECK (status IN ('present', 'absent', 'excused')),
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Payroll / Payments (Simplified)
CREATE TABLE payments (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES users(id), -- Instructor receiving or Student paying
    amount DECIMAL(10, 2) NOT NULL,
    type VARCHAR(20) CHECK (type IN ('salary_payout', 'tuition_fee')),
    status VARCHAR(20) DEFAULT 'pending',
    date TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
